### ISSUE TITLE
glitch in flooding status

### ISSUE THREAD

**Issue by jieAmple** [USEPA/Stormwater-Management-Model#175]
[scenario_c_swmm.zip](https://github.com/USEPA/Stormwater-Management-Model/files/15084436/scenario_c_swmm.zip)
I have a glitch to report that the junction E1 is reported as flooded status in the panel, while in there is no flooding in flood summary (see below)
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/114220970/5c5f2636-663a-4d07-ba19-fedb4d57e530)
the issue can be corrected by assigning any non zero value to ponded area at E1. But I do hope this glitch can be revised in the swmm engin

**Comment by MitchHeineman** [comment]
I see your point about how Flooding Loss in the Continuity summary is reported as 10.264 million liters. I won't judge whether your very unusual configuration warrants a code change. It appears to me that the flooding is at the very start of the simulation when depth in E1 jumps from 0 to 103.08. If you instead set an initial depth of 103.08, no flooding will occur.

I'll also note that you posted a PCSWMM package. While the issue you observed is not specific to PCSWMM, you should instead raise questions first with the vendor instead of posting here. When you do use this forum, post the .inp file, not the vendor's .pcz format file (although it is simply a .zip file with a custom extension), so that it is more obviously readable by any SWMM user.

**Comment by dickinsonre** [comment]
I agree with Mitch  a numerical model is a numerical engine  subject to initial conditions.  If the initial conditions are off, then odd things can happen for a few time steps.  It sounds as if SWMM5 fixed the issue as it should.

**Comment by dickinsonre** [comment]
you also do not start reporting the results for 30 minutes so you miss the flooding right at the beginning of the simulation  - which is the reason there was no reported flooding  - the flooding occurs in the first minutes.  It looks like the summary table only shows information AFTER the start of the reported results.  
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/5599939/23bf472d-5d90-4070-b377-6fb795717c1f)

**Comment by cbuahin** [comment]
@jieAmple , I believe @dickinsonre's plot and explanation addresses the issue you are observing. It appears it is not a bug so I will mark this issue as resolved unless you have additional questions.
