### ISSUE TITLE
Conduit loss calculation

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#27]
In dynamic wave routing, the conduit loss calculation seems to have some issues. The loss should apply the flow-to node, not the flow-from node. Otherwise, the routing continuity error will increase.

1. From updateNodeFlows() in dynwave.c (SWMM5.1.013)

    // --- update total inflow & outflow at upstream/downstream nodes
    if ( q >= 0.0 )
    {
        Node[n1].outflow += q + uniformLossRate;
        Node[n2].inflow  += q;
    }
    else
    {
        Node[n1].inflow   -= q;
        Node[n2].outflow  -= q - uniformLossRate;
    }

The above code should be:

if ( q >= 0.0 )
    {
	Node[n1].outflow += q;
        Node[n2].inflow  += q - uniformLossRate;
    }
    else
    {
        Node[n1].inflow   -= q + uniformLossRate;
        Node[n2].outflow  -= q;
    }

2. Where to apply number of barrels?
       uniformLossRate = (Conduit[k].evapLossRate + Conduit[k].seepLossRate)***barrels**;

3. Loss should be cleared when the conduit is dry in dwflow_findConduitFlow():
if ( Link[j].flowClass == DRY ||
         Link[j].flowClass == UP_DRY ||
         Link[j].flowClass == DN_DRY ||
         isClosed ||
         aMid <= FUDGE )
    {
        Conduit[k].a1 = 0.5 * (a1 + a2);
        Conduit[k].q1 = 0.0;;
        Conduit[k].q2 = 0.0;

	**Conduit[k].evapLossRate = 0;
	Conduit[k].seepLossRate = 0;**

        Link[j].dqdh  = GRAVITY * dt * aMid / length * barrels;
        Link[j].froude = 0.0;
        Link[j].newDepth = MIN(yMid, Link[j].xsect.yFull);
        Link[j].newVolume = Conduit[k].a1 * link_getLength(j) * barrels;
        Link[j].newFlow = 0.0;
        return;
    }

Please see the following input file for example (rename it to .inp file):

[Evaporation.txt](https://github.com/USEPA/Stormwater-Management-Model/files/3636565/Evaporation.txt)

**Comment by Tiehong** [comment]
The function name of issue 3 is dwflow_findConduitFlow()

**Comment by dickinsonre** [comment]
Interesting, have you compared the loss code in EPA SWMM 5.1.013 to past EPA SWMM 5 codes and EPA SWMM 5 model results?  SWMM5 can handle .txt so you do not have to rename the file.

**Comment by Tiehong** [comment]
Good point. I compared the loss code to past SWMM5 code. The code can be traced back to SWMM5.1.001. SWMM5.0 are quite different, which does not support evaporation and seepage yet.

The issue was triggered by running continuous simulation on a 2D model, which contains large number of open channels. The evaporation during dry periods introduced high routing continuity error. This simple model is to create for easy debugging, where I found the three potential issues.

**Comment by LRossman** [comment]
The fix recommended by @Tiehong was implemented in release 5.1.014. However the change in how the `uniformLossRate `was applied to a conduit's end nodes was producing incorrect results so in 5.1.015 it was rolled back to the original code.

**Comment by LRossman** [comment]
Mitch Heineman sent me an input file that had an orphan conduit with junctions at both ends with no inflow and initial depths of 5 and 4.99 ft, respectively. Below are plots of flow and depth both without and with a seepage rate included. (Because the conduit has no outfall the initial depth difference at the end nodes causes a wave disturbance to bounce back and forth along its length).

![image](https://github.com/USEPA/Stormwater-Management-Model/assets/12769926/e961bdd8-ff38-4f8d-945f-b459fd5db4d2) 
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/12769926/d2fc8989-ddde-4ac1-96fa-640e33012ce1)

The original SWMM (v.5.2.3) results for the seepage case show a nonlinear drop in depth when it should be linear (since the seepage rate is constant) and an unrealistic increase in the amplitude of the wave disturbance (with flows as high as +- 40 cfs). To correct this issue I made the following changes to the dynamic wave code:

1. The combined conduit loss rate (evap. + seepage) is now limited by the conduit's current water volume and not its flow rate.
2. The loss rate is now split evenly between the outflow accumulated at each of its end nodes instead of applied just at the upstream node.

With these changes the results for the case with seepage look much better as shown below (there was no change in results for the no-seepage case):

![image](https://github.com/USEPA/Stormwater-Management-Model/assets/12769926/31bf0848-745f-457b-adf4-15af8315f1d2)

A PR that implements these changes will be submitted shortly.

**Comment by dickinsonre** [comment]
If you take Mitch's seepage model and run it a a report time step of 1 minute you get one of the model interesting flow graphs I have ever seen.  The water is just sloshing from one end to the other end of the link.  The slightest difference starts the sloshing 5 vs 4.999 for example as the starting node depths
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/5599939/97d1e200-36c5-408f-bdd2-a02d7ca515d4)

**Comment by LRossman** [comment]
Looks like a fractal drawing :astonished: .

**Comment by cbuahin** [comment]
Addressed in #125. A dampening factor will be added to the infiltration max in future versions.
