### ISSUE TITLE
Default infiltration value (Green & Ampt methods)

### ISSUE THREAD

**Issue by MikeGregory-Canada** [USEPA/Stormwater-Management-Model#63]
The default value for Initial Deficit is incorrectly entered by the interface for the G&A and modified G&A methods.
![image](https://user-images.githubusercontent.com/70409362/92800601-d4d13580-f382-11ea-8ee3-d25e3bd26ac5.png)

**Comment by dickinsonre** [comment]
oh yes, i was wondering where those 4's were coming from in our test models - it was my making of the test models.  Thanks for finding this @MikeGregory-Canada  of Canada/Florida

**Comment by MitchHeineman** [comment]
That's an issue in the GUI (I don't think that's in GitHub), which seems to be solved in version 5.1.015. However, I think there's also a problem in the engine. 4 is accepted without flagging a warning or error AND it produces results different from if one specifies IMD=1. The issue is the same for G-A and modified G-A. The working example below yields 0.66" pervious runoff for IMD=0.25, 0.25" for IMD=1, and no pervious runoff for IMD=4.

[TITLE]
Initial moisture deficit bug: IMD greater than 1 yields results different from IMD=1

[OPTIONS]
FLOW_UNITS           CFS
INFILTRATION         MODIFIED_GREEN_AMPT
START_DATE           07/17/2018
END_DATE             07/18/2018

[RAINGAGES]
;;Name           Format    Interval SCF      Source    
MHT              VOLUME    1:00     1.0      TIMESERIES MHT             

[SUBCATCHMENTS]
;;Name           Rain Gage        Outlet           Area     %Imperv  Width    %Slope   CurbLen  SnowPack        
IMDNormal        MHT              IMDNormal        5        50       500      0.5      0                        
IMD1             MHT              IMD1             5        50       500      0.5      0                        
IMD4             MHT              IMD4             5        50       500      0.5      0                        

[SUBAREAS]
;;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted 
IMDNormal        0.02       0.1        0.05       0.15       25         Perv       50        
IMD1             0.02       0.1        0.05       0.15       25         Perv       50        
IMD4             0.02       0.1        0.05       0.15       25         Perv       50        

[INFILTRATION]
;;Subcatchment   Param1     Param2     Param3     Param4     Param5    
IMDNormal        3.5        0.5        0.25                            
IMD1             3.5        0.5        1                               
IMD4             3.5        0.5        4                               

[TIMESERIES]
;;Name   Date Time   Value     
MHT 7/17/2018 11:00  0.01  
MHT 7/17/2018 12:00  2.20  
MHT 7/17/2018 13:00  0.10  
MHT 7/17/2018 14:00  0.15  
MHT 7/17/2018 15:00  0.16  
MHT 7/17/2018 16:00  0.18  
MHT 7/17/2018 17:00  0.16  
MHT 7/17/2018 18:00  0.04  
MHT 7/17/2018 20:00  0.06  
MHT 7/17/2018 21:00  0.02

**Comment by cbuahin** [comment]
I believe this issue has been addressed.  Also, the [GUI](https://github.com/USEPA/SWMM-GUI) has its own repo now so please consider raising GUI related bugs there in the future. Thank you for raising this issue!

**Comment by MitchHeineman** [comment]
As this issue caused me a huge headache on a project a few years ago, I checked it to be sure. It was indeed addressed in Engine Update #8 in 5.2.0
