### ISSUE TITLE
Rainfall plot and event statistics

### ISSUE THREAD

**Issue by MikeGregory-Canada** [USEPA/Stormwater-Management-Model#69]
The rainfall plot and event statistics are incorrect when the reporting step is greater than the recording interval. See attached file, which features a bunch of 1-minute pulses of rain, each is 0.2” (12 in/hr) and irregularly spaced in time. MillDistrictMN_Oct2011.inp <<saved as *.txt file>>

[MillDistrictMN_Oct2011.txt](https://github.com/USEPA/Stormwater-Management-Model/files/6151108/MillDistrictMN_Oct2011.txt)

With a 15-min reporting step, the Total Precip. in the Summary Results table is correctly reported as 3.20 in, however the graph only plots the first and last pulse (these are the only two pulses that begin exactly on the 15-min reporting period). Likewise, the event statistics are incorrectly calculated: only two events are detected, and the Event Total assumes that the 12 in/hr intensity lasts for a duration of 15 min (i.e., 3” in each pulse). When you change the reporting step to 1 min (same as the rainfall recording interval), all rainfall pulses are correctly plotted and event statistics correctly calculated.

I could live with the graphical error when plotting such timeseries, but not the errors in event statistics. As it becomes more common to use 1-min ASOS rainfall data, it is still practical to go with a larger reporting step of 15-min or more to limit the output file size. So, this error will become more persistent – but the error is not evident unless you deliberately go hunting for it. This is a concern.

**Comment by MikeGregory-Canada** [comment]
![image](https://user-images.githubusercontent.com/70409362/111353679-ea8a2500-865b-11eb-9c05-5609d99451b3.png)
![image](https://user-images.githubusercontent.com/70409362/111353724-f37af680-865b-11eb-9da8-375266ef3516.png)

**Comment by dickinsonre** [comment]
A problem obviously, but if you only save every 15 minutes how are the stats and graph code in SWMM5 supposed to know there was rainfall in between?  Have you tried to use the average time step report option?

**Comment by LRossman** [comment]
If you are just interested in getting an accurate statistical picture of rainfall events then you could run the model using the rainfall interval as the reporting step and turn off flow routing. And if that still produces too much output, you could create a "rainfall-only" model with just the original rain gage, its 1-minute rainfall data, and a dummy subcatchment connected to it.

To get more meaningful reported results with 1-minute rainfall and a larger reporting step would require some changes to the code. Here are some options:

1. Extend the average time step report option to subcatchments (right now it only applies to node and link output) or add a separate average time step report option for subcatchments (so that flow routing peaks won't be lost due to all results being averaged).

2. Allow the rainfall time series to be accumulated to what the user designates as the series recording time interval in the rain gage's properties (e.g., if the user specifies a 5-minute time interval for rainfall then have the program use the average of each 5 consecutive 1-minute readings for its rainfall). Currently if the program sees a recording time interval greater than the time series interval it issues a fatal error condition.

Obviously there's some information loss with each of these options.

**Comment by dickinsonre** [comment]
I would consider it a user error if the user wants to see information at intervals less than the report time step.  If you add rainfall averaging or other workarounds you will further confuse users.  A user not understanding the implications of the report time step is common in a lot of software - not just SWMM5.

**Comment by MikeGregory-Canada** [comment]
These are great suggestions, thanks. You’ve convinced me - this is not a bug, but more like a misuse of the model. I’ll close this issue (and include this material in future training sessions on model troubleshooting).
