### ISSUE TITLE
Fix Actions on lew-develop branch

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/Stormwater-Management-Model#77]
@LRossman Actions is currently down. I'm going to make some commits to the lew-develop branch to fix it. Thanks in advance for you cooperation.

**Comment by michaeltryby** [comment]
@LRossman Upon examination of the lew-develop branch it appears that there are duplicate versions of the swmm-solver source codes present there. 

On Nov 15 Release 5.2.0 was pushed into src/solver branch. Then on Nov 29 Release 5.2.0 - updated and Release 5.2.0 - API fixes were pushed into src/. 

Should I assume that the version in the src/ is the definitive version you intend for release? Please clarify your intent. Thanks!

**Comment by LRossman** [comment]
Sorry about mixing up the `src` directory with the` src/solver` directory.  The definitive 5.2.0 files have all been placed in `src` (which is where they reside on my development machine and is what my `CMakeLists.txt` file expects). Let me know if you would like me to clean things up, and which directory structure to use (everything in `src `or distributed between `src/solver`, `src/include` and `src/run`).

**Comment by michaeltryby** [comment]
@LRossman I got the source code straightened out. What version of Visual Studio are you using to build  SWMM these days?

**Comment by LRossman** [comment]
Visual Studio 2019.

**Comment by michaeltryby** [comment]
@LRossman are you building SWMM 32 bit, 64 bit, or both? Thanks!

**Comment by LRossman** [comment]
Both, since the Delphi GUI code can now be compiled to 64-bit. Please see my CMakeLists file. For 32-bit, `swmm5.def` has to be included as a  Module Definition File in order for the GUI code to recognize the `swmm5.dll` functions. But this is not required for 64-bit (why, I don't know). Also note that I've built using a static link of the runtime library (`add_definitions (-MT)` in the CMakeLists file) so that the library doesn't have to be installed by the installation program (only the correct version of the OpenMP DLL needs to be distributed).

**Comment by michaeltryby** [comment]
@LRossman So the GUI has been upgraded to 64bit? Nice work! I understand that it is your preference to static link swmm solver with system libraries. Current recommendation from Microsoft, however, is to dynamic link and include system libraries with installation. Please familiarize yourself with information found in links below. Happy to discuss further. Thanks!
 
https://docs.microsoft.com/en-us/cpp/windows/choosing-a-deployment-method?view=msvc-170
https://docs.microsoft.com/en-us/cpp/windows/redistributing-the-mfc-library?view=msvc-170
